# Generated by Django 5.0.3 on 2024-03-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('conteudo', models.TextField()),
                ('data', models.DateField(help_text='dd/mm/aaaa')),
                ('destaque', models.BooleanField()),
                ('imagem', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('titulo', models.TextField()),
            ],
        ),
    ]
