# Generated by Django 5.0.3 on 2024-03-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('Esporte', 'Esporte'), ('Cultura', 'Cultura'), ('Economia', 'Economia')], max_length=50),
        ),
    ]
